# Generated by Django 6.0.5 on 2026-06-02 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL-слаг')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название сервиса')),
                ('default_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Базовая стоимость')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='subscriptions.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Шаблон сервиса',
                'verbose_name_plural': 'Шаблоны сервисов',
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Кастомное название')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость подписки')),
                ('billing_period', models.CharField(choices=[('monthly', 'Раз в месяц'), ('yearly', 'Раз в год')], default='monthly', max_length=10, verbose_name='Периодичность списания')),
                ('next_billing_date', models.DateField(verbose_name='Дата следующего списания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Статус (активна)')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.subscriptionservice', verbose_name='Сервис из каталога')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Подписка пользователя',
                'verbose_name_plural': 'Подписки пользователей',
                'ordering': ['next_billing_date'],
            },
        ),
    ]
